#!/bin/bash
# Scenario 44: migrate-vN-to-vM live rig (P3 Stage 3 — migration + integration).
#
# The concrete instance for the only migration that currently exists (N=11,
# M=12: the two per-user tables user_prefs + user_hidden_items + the index
# idx_user_hidden_items_user; REQ-M14-PER-USER, branch B). A future schema bump
# ships its own NN-migrate-v12-to-v13.sh re-using this exact shape.
#
# *** OPERATOR-RUN-ONLY *** (needs the patched channel-arch Jellyfin +
# a plugin DLL built from this branch). Rig :18096 ONLY, never prod.
#
# What this proves, end to end (structural pass is NOT enough — a real vM
# plugin boots on the migrated DB and the full downstream e2e passes AGAINST
# the migrated DB):
#
#   [1] SEED — start from a vN (v11) SYNTHETIC phantom.db. The seed is derived
#       purely from the synthetic-provenance v12 fixture that scenario
#       41-discovery-from-empty exports (zero operator PII), DOWNGRADED to v11
#       by dropping exactly the two v12 objects. If that fixture is absent it
#       is regenerated by running scenario 41 first.
#   [2] CENSUS-BEFORE — record every pre-existing table's row count + a content
#       fingerprint on the v11 seed.
#   [3] MIGRATE — run scripts/phantom-migrate-v11-to-v12.sh --commit against a
#       clone and assert: exit 0; user_version 11 -> 12; user_prefs +
#       user_hidden_items + idx_user_hidden_items_user now present and the two
#       new tables EMPTY; every pre-existing table byte/census-identical to the
#       before-fingerprint (the migration is additive-only); the migrated
#       schema is IDENTICAL to a freshly-built v12 DB; and the script's own
#       predicted-before / actual-after verification agrees (predicted==actual).
#   [4] BOOT vM — install the MIGRATED phantom.db into the rig and boot the vM
#       plugin on it (rig-up). Assert the plugin comes up on the migrated DB
#       (schema stays v12, no re-wipe, no re-migration) and the per-user tables
#       survive the boot.
#   [5] FULL DOWNSTREAM E2E — against the MIGRATED DB, run the real downstream
#       scenarios: 35 (movie e2e), 36 (episode e2e) and 42 (per-user show/hide,
#       which exercises exactly the user_prefs / user_hidden_items tables the
#       migration created). Their own OK markers gate this scenario.
#
# The equivalent DETERMINISTIC (no-live-Jellyfin) invariants of steps [1]-[3]
# are regression-covered in-repo by scripts/tests/migration-rig.test.sh (the
# build/unit-test-tier guard, runnable with only bash + sqlite3). This scenario
# is the LIVE proof that a real vM plugin actually runs on the migrated DB.
#
# CI: driven by the Gitea Actions job `phantom-library-migration-rig`
# (.gitea/workflows/migration-rig.yml) on the self-hosted runner. Synthetic
# fixture only; trap-based cleanup.

set -u
mkdir -p /tmp/jf-rig/logs
exec > >(tee /tmp/jf-rig/logs/scenario-migrate-v11-to-v12.log) 2>&1

ROOT=${PHANTOM_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}
RIG=/tmp/jf-rig
API=${BASE:-http://localhost:18096}
TOK=${TOK:-testtoken00000000000000000000000}
PHDB=${PHDB:-/tmp/jf-test/data/plugins/configurations/PhantomLibrary/phantom.db}
MIGRATE="$ROOT/scripts/phantom-migrate-v11-to-v12.sh"
FIXTURE_DIR="$RIG/fixtures/discovery-from-empty"
WORK="$RIG/state/migrate-v11-to-v12"
FROM_VERSION=11
TO_VERSION=12

echo "=== Scenario 44: migrate v${FROM_VERSION} -> v${TO_VERSION} live rig ==="
date
echo

fail() { echo "FAIL: $*" >&2; exit 1; }

# ---------------------------------------------------------------- trap-clean
cleanup() {
  local rc=$?
  echo "[cleanup] tearing down rig (rc=$rc)"
  bash "$ROOT/tools/rig-scenarios/rig-down.sh" >/dev/null 2>&1 || true
  rm -rf "$WORK" 2>/dev/null || true
}
trap cleanup EXIT

command -v sqlite3 >/dev/null 2>&1 || fail "sqlite3 required"
[ -x "$MIGRATE" ] || fail "migration script not found/executable: $MIGRATE"

uv()      { sqlite3 "$1" 'PRAGMA user_version;'; }
has_tbl() { [ "$(sqlite3 "$1" "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='$2';")" = "1" ]; }
has_idx() { [ "$(sqlite3 "$1" "SELECT COUNT(*) FROM sqlite_master WHERE type='index' AND name='$2';")" = "1" ]; }
schema_fingerprint() {
  sqlite3 "$1" "SELECT type,name,COALESCE(sql,'') FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' ORDER BY type,name;"
}
# per-table content fingerprint (order-stable) for every pre-existing user table.
user_tables() {
  sqlite3 "$1" "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name;"
}
census() {  # census <db> ; prints 'table<TAB>rowcount' for each pre-existing table
  local db="$1" t
  for t in $(user_tables "$db"); do
    printf '%s\t%s\n' "$t" "$(sqlite3 "$db" "SELECT COUNT(*) FROM \"$t\";")"
  done
}

mkdir -p "$WORK"

# =====================================================================
echo "[1] obtain the synthetic v${TO_VERSION} fixture, downgrade to v${FROM_VERSION} seed"

if [ ! -s "$FIXTURE_DIR/phantom.db" ]; then
  echo "  synthetic fixture absent; regenerating via scenario 41-discovery-from-empty"
  bash "$ROOT/tools/rig-scenarios/41-discovery-from-empty.sh" \
    || fail "could not generate synthetic v${TO_VERSION} fixture (scenario 41 failed)"
fi
[ -s "$FIXTURE_DIR/phantom.db" ] || fail "synthetic fixture still missing: $FIXTURE_DIR/phantom.db"

SEED_V11="$WORK/seed-v11.db"
REF_V12="$WORK/ref-v12.db"
sqlite3 "$FIXTURE_DIR/phantom.db" ".backup '$REF_V12'"
[ "$(uv "$REF_V12")" = "$TO_VERSION" ] || fail "fixture is not v${TO_VERSION} (got v$(uv "$REF_V12"))"

# Downgrade a copy to v11: drop EXACTLY the two v12 objects + the index.
sqlite3 "$FIXTURE_DIR/phantom.db" ".backup '$SEED_V11'"
sqlite3 "$SEED_V11" "DROP INDEX IF EXISTS idx_user_hidden_items_user;
                     DROP TABLE IF EXISTS user_hidden_items;
                     DROP TABLE IF EXISTS user_prefs;
                     PRAGMA user_version=${FROM_VERSION};"
[ "$(uv "$SEED_V11")" = "$FROM_VERSION" ] || fail "seed downgrade failed (v$(uv "$SEED_V11"))"
has_tbl "$SEED_V11" user_prefs && fail "seed still has user_prefs (downgrade incomplete)"
echo "  v${FROM_VERSION} synthetic seed built from the zero-PII discovery fixture"

# =====================================================================
echo "[2] census-before on the v${FROM_VERSION} seed"
BEFORE_CENSUS="$WORK/census-before.txt"
BEFORE_FP="$WORK/schema-before.txt"
census "$SEED_V11" > "$BEFORE_CENSUS"
schema_fingerprint "$SEED_V11" > "$BEFORE_FP"
[ -s "$BEFORE_CENSUS" ] || fail "empty census-before (seed has no tables?)"
echo "  recorded $(wc -l < "$BEFORE_CENSUS") pre-existing tables"

# =====================================================================
echo "[3] migrate the clone --commit and assert additive correctness"
CLONE="$WORK/migrated.db"
cp -p "$SEED_V11" "$CLONE"

# The script prompts for a typed MIGRATE confirmation on --commit; feed it.
printf 'MIGRATE\n' | PHANTOM_DB="$CLONE" bash "$MIGRATE" --skip-service-check --commit \
  || fail "migration script exited non-zero (its own predicted==actual verification failed)"

[ "$(uv "$CLONE")" = "$TO_VERSION" ] || fail "user_version not ${TO_VERSION} (got $(uv "$CLONE"))"
has_tbl "$CLONE" user_prefs        || fail "user_prefs missing after migrate"
has_tbl "$CLONE" user_hidden_items || fail "user_hidden_items missing after migrate"
has_idx "$CLONE" idx_user_hidden_items_user || fail "index missing after migrate"
[ "$(sqlite3 "$CLONE" 'SELECT COUNT(*) FROM user_prefs;')" = "0" ] \
  && [ "$(sqlite3 "$CLONE" 'SELECT COUNT(*) FROM user_hidden_items;')" = "0" ] \
  || fail "new tables are not empty"

# every PRE-EXISTING table byte/census-identical (additive-only).
AFTER_CENSUS="$WORK/census-after.txt"
# restrict the after-census to the tables that existed before the migration.
: > "$AFTER_CENSUS"
while IFS=$'\t' read -r t _; do
  printf '%s\t%s\n' "$t" "$(sqlite3 "$CLONE" "SELECT COUNT(*) FROM \"$t\";")" >> "$AFTER_CENSUS"
done < "$BEFORE_CENSUS"
diff -u "$BEFORE_CENSUS" "$AFTER_CENSUS" \
  || fail "a pre-existing table's row count changed across the migration (not additive)"

# migrated schema IDENTICAL to a freshly-built v12 DB (parity).
[ "$(schema_fingerprint "$CLONE")" = "$(schema_fingerprint "$REF_V12")" ] \
  || fail "migrated schema differs from a fresh v${TO_VERSION} DB"
echo "  migrate OK: v11->v12, new tables empty, pre-existing tables census-identical, schema parity, predicted==actual"

# =====================================================================
echo "[4] boot the vM plugin on the MIGRATED DB"
# EPOCH GATE (honest red, never a silent green — same posture as the Zuul job,
# see docs/ci-zuul.md). The live plugin HARD-REFUSES any phantom.db below its
# PhantomDb.CurrentSchemaVersion (AGENTS.md "No database migrations until v1.0":
# pre-vCURRENT DBs are refused, wipe required). The only in-repo additive
# migration is v11 -> v12. So a real vM plugin can boot the MIGRATED DB and run
# the full downstream e2e ONLY while the migration's target (M=12) equals the
# live plugin's CurrentSchemaVersion. When the plugin schema has advanced past
# M (as it does once a later bump lands), that additive migration no longer
# reaches the current schema, and this live-boot half is HONESTLY RED until the
# in-repo migration is advanced to the current schema — never faked green.
PHANTOMDB_CS="$ROOT/src/Jellyfin.Plugin.PhantomLibrary/State/PhantomDb.cs"
CURRENT_SCHEMA="$(grep -oE 'CurrentSchemaVersion *= *[0-9]+' "$PHANTOMDB_CS" | grep -oE '[0-9]+' | head -1)"
[ -n "$CURRENT_SCHEMA" ] || fail "could not read PhantomDb.CurrentSchemaVersion from $PHANTOMDB_CS"
echo "  migration target M=${TO_VERSION}; live plugin CurrentSchemaVersion=${CURRENT_SCHEMA}"

if [ "$TO_VERSION" != "$CURRENT_SCHEMA" ]; then
  cat >&2 <<EOF
FAIL: epoch mismatch — the in-repo additive migration targets v${TO_VERSION} but the
      live plugin is at schema v${CURRENT_SCHEMA}, which HARD-REFUSES a v${TO_VERSION} DB at startup
      (AGENTS.md "No database migrations until v1.0"). The DETERMINISTIC additive
      migration proof above (steps [1]-[3], regression-covered by
      scripts/tests/migration-rig.test.sh) PASSED, but the live boot + full
      downstream e2e cannot run until the in-repo migration reaches v${CURRENT_SCHEMA}
      (a new additive phantom-migrate-v${TO_VERSION}-to-v${CURRENT_SCHEMA}.sh, or an advanced chain).
      This is honest red, never a silent green.
EOF
  exit 1
fi

mkdir -p "$(dirname "$PHDB")"
cp -p "$CLONE" "$PHDB"
bash "$ROOT/tools/rig-scenarios/rig-up.sh" --reset || fail "rig-up failed to boot on migrated DB"

# The rig must NOT re-wipe or re-migrate: schema stays at M, per-user tables survive.
[ "$(uv "$PHDB")" = "$TO_VERSION" ] || fail "rig phantom.db is not v${TO_VERSION} after boot (got v$(uv "$PHDB"))"
has_tbl "$PHDB" user_prefs        || fail "user_prefs vanished after boot"
has_tbl "$PHDB" user_hidden_items || fail "user_hidden_items vanished after boot"

# plugin is live over HTTP.
curl -sf -H "X-Emby-Token: $TOK" "$API/System/Info" >/dev/null \
  || fail "rig Jellyfin not answering on $API after boot on migrated DB"
echo "  vM plugin is live on the migrated DB (schema v${TO_VERSION} intact)"

# =====================================================================
echo "[5] full downstream e2e AGAINST the migrated DB (35 + 36 + per-user 42)"
# The rig is already up on the migrated DB; run the downstream scenarios with
# NO reset so they exercise the MIGRATED phantom.db, not a fresh one.
RIG_NO_RESET=1 bash "$ROOT/tools/rig-scenarios/35-channel-e2e-playback.sh" \
  || fail "downstream 35-channel-e2e-playback failed on the migrated DB"
RIG_NO_RESET=1 bash "$ROOT/tools/rig-scenarios/36-channel-episode-e2e-playback.sh" \
  || fail "downstream 36-channel-episode-e2e-playback failed on the migrated DB"
RIG_NO_RESET=1 bash "$ROOT/tools/rig-scenarios/42-per-user-show-hide.sh" \
  || fail "downstream 42-per-user-show-hide failed on the migrated DB"
echo "  full downstream e2e PASSED against the migrated DB"

echo
echo 'MIGRATION_RIG_OK'
